# Target device
MCU = attiny85
F_CPU = 1000000
LFUSE = 0x62
HFUSE = 0xDF
EFUSE = 0xFF

# Application files and targets
TARGET = ir

# Place -I options here
CINCS = 
CXXINCS = 

# Place extra C/CXX arguments here
CEXTRA = 
CXXEXTRA = 

# Source files for C compiler
SRC = main.c

# Source files for C++ compiler
CXXSRC = 

# Source files in assembly
ASRC =

# This includes the rest of rules DO NOT DELETE
-include ../../Makefile.avr.inc
-include ~/.gEDA/Makefile.avr.inc
